version: "3.8"
services:
    db:
        container_name: postgres_container
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: test_db
        ports:
            - "5432:5432"
        networks:
            - backend_network

    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "5050:80"
        networks:
            - backend_network

    app:
        container_name: mcp-untitled-server-container
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - db
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test_db
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
        ports:
            - "8081:8081"
        networks:
            - backend_network

networks:
    backend_network:
        driver: bridge
