package com.example.mcp_untitled_server.domain.transaction.transactionExpenseRecurrent;

import org.springframework.stereotype.Repository;

@Repository
class TransactionExpenseRecurrentRepositoryCustomImpl implements TransactionExpenseRecurrentRepositoryCustom {
}
